import freeimage,\
            FreeImage_Initialise,'_FreeImage_Initialise@4',\
            FreeImage_DeInitialise,'_FreeImage_DeInitialise@0',\
            FreeImage_Load,'_FreeImage_Load@12',\
            FreeImage_Unload,'_FreeImage_Unload@4',\
            FreeImage_GetBits,'_FreeImage_GetBits@4',\
            FreeImage_ConvertToType,'_FreeImage_ConvertToType@12',\
            FreeImage_GetFileType,'_FreeImage_GetFileType@8',\
            FreeImage_GetWidth,'_FreeImage_GetWidth@4',\
            FreeImage_GetHeight,'_FreeImage_GetHeight@4',\
            FreeImage_GetBPP,'_FreeImage_GetBPP@4',\
            FreeImage_ConvertTo32Bits,'_FreeImage_ConvertTo32Bits@4',\
            FreeImage_FlipHorizontal,'_FreeImage_FlipHorizontal@4'
            